api_hash: your_api_hash
api_id: your_api_id
chat_id: telegram_chat_id
drive_id: google drive url (only google drive cloud service is supported)
drive_name: fclone drive remote
sleep_interval: optional, defaults to 20 if left empty
last_read_message_id: 0
ids_to_retry: []
media_types:
- audio
- photo
- video
- document
- voice
- video_note
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
